name: flutter_ddd
description: "A Very Good Project created by Very Good CLI."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cli_completion: ^0.5.1
  yaml_magic: ^1.0.6
  mason: ^0.1.0
  args: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  mocktail: ^1.0.4
  build_verify: ^3.1.0
  mockito:
  test:
