name: "Test Package"
description: "Runs tests and collects coverage for Flutter package"

runs:
  using: "composite"
  steps:
    - name: Install lcov
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y lcov
    
    - name: Run tests with coverage
      shell: bash
      run: flutter test --coverage
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: HamzaChekar123/flutter_ddd