name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      flutter-version: "3.29.0"
    steps:
      - uses: actions/checkout@v3
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2
      

  verify:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Install Dependencies
        run: flutter pub get
      
      - name: Analyze project
        uses: ./.github/actions/analyze-package


  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Install Dependencies
        run: flutter pub get 
      - name: Run Tests
        run: flutter test
        timeout-minutes: 5
      

  build-and-test-package:
    name: Build and test package on ${{ matrix.os }}
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Package
        uses: ./.github/actions/build-package
        
      